### ISSUE TITLE
Textwrap "i is undefined" error

### ISSUE THREAD

**Issue by msatkevich** [alexandersimoes/d3plus#241]
Hi,

For some of my data sets, the following code errors on line 18461:

for (_i = 0, _len = words.length; _i < _len; _i++) {
    word = words[_i];
    if (line * textHeight > vars.height.value) {
      textBox.remove();
      if (i !== 1) {
        textBox = d3.select(vars.container.value.node().lastChild);
        if (!textBox.empty()) {
          truncate();
        }
      }
      break;
    }

This results in i is undefined error.

Notice it is i instead of _i.  Not sure if that's a bug or not.

**Comment by davelandry** [comment]
This is (was) an issue related to text wrapping. I *believe* this has been fixed along with some other textwrap bugs since the last release. Can you try loading your tree map with the current development build in the main repository and see if the error still occurs?

Develeopment Build: https://raw.githubusercontent.com/alexandersimoes/d3plus/master/d3plus.js

**Comment by davelandry** [comment]
v1.6.8 has been released, which fixed this problem.

**Comment by msatkevich** [comment]
Thanks!

It works in Chrome consistently now.

However, in IE, some data sets throw this error:


SCRIPT65535: Unexpected call to method or property access.
File: d3plus.js, Line: 18467, Column: 9

**Comment by msatkevich** [comment]
Thanks!

It works in Chrome consistently now.

However, in IE, some data sets throw this error:


SCRIPT65535: Unexpected call to method or property access.
File: d3plus.js, Line: 18467, Column: 9

**Comment by davelandry** [comment]
Please post this as a new issue.
