### ISSUE TITLE
Titles in non-english gets 2 capital letters at the beginning

### ISSUE THREAD

**Issue by Jabher** [alexandersimoes/d3plus#247]
E.g. if I have a code like 
```javascript
//...
var sample_data = [/*...*/
            {"name": "role", "title": "Роль", "size": 40, "class": "level2"}
                /*...*/],
connections = [/*...*/];

d3plus.viz()
                .container("#viz")
                .type("network")
                .data(sample_data)
                .edges(connections)
                .edges({"arrows": true})
                .id("name")
                .text("title")
                .draw();
```

Word 'Роль' turns into ' РОль' in render.

The following code causes this problem:
https://github.com/alexandersimoes/d3plus/blob/master/src/string/title.coffee#L19

```coffeescript
prefix = txt.charAt(0).search(/[^A-Za-z0-9\-_]/g) is 0
```

Actually, JavaScript does not support full range unicode match character, so the following RegExp would be much more appropriate in order to support i18n:
```coffeescript
prefix = txt.charAt(0).search(/[^\W\s]/g) is 0
```
It performs a check if the first letter is neither non-letter character (\W) nor space (\s)

Moreover, instead of following code
```coffeescript
    prefix = txt.charAt(0).search(/[^A-Za-z0-9\-_]/g) is 0

    if prefix
      prefix = txt.charAt(0)
      txt = txt.slice(1)
    else
      prefix = ""
```
you could use
```coffeescript
    if /^[^\W\s]/.test(txt)
      prefix = txt.charAt(0)
      txt = txt.slice(1)
    else
      prefix = ""
```

which works faster and looks simplier.

**Comment by davelandry** [comment]
Wow, good find and great solution. Would you mind creating a pull request with this code change? I'd love to have you recorded as the contributor for this.

**Comment by Jabher** [comment]
Sure, you're welcome: https://github.com/alexandersimoes/d3plus/pull/248

Actually, the whole file can be simplified and optimized at least twice, but I'm actually kind of scary to edit the project - there are no tests, so I don't know how to check that all of the test cases still works

**Comment by davelandry** [comment]
I hear you man. I feel the same way when I edit some of these files. The whole project grew very rapidly.

This title case function would be easy to create some simple test cases for, but I've been looking for a testing library that's more cross-browser based because D3plus is tied so closely to the visuals rendered in browser. I've been looking into using DalekJS (http://dalekjs.com) for creating a comprehensive set of tests.

We're probably going to do 1 more big sprint into developing new features, and then I'm hoping to spend some time on tests and code documentation.

**Comment by ssjsatish** [comment]
Going forward with this thread. I have nodes having names like `{'source':'ALPHA','target':'BETA','source':'DBS','target':'CDN','source':'Cross Platform','target':'Primary OS'}`
I needed the 'source' and `target` to be same as they are in `connections` so I removed `toLowerCase` from the above code. Would there be any impact somewhere else because till now its working as I wanted. Please suggest.

**Comment by davelandry** [comment]
@ssjsatish instead of modifying the internal source code, you should be overriding the default text formatting function: http://d3plus.org/examples/advanced/7760febcda3375b39e1f/
