### ISSUE TITLE
d3plus.string.title should format "CPU" correctly

### ISSUE THREAD

**Issue by zpz1982** [alexandersimoes/d3plus#295]
why the default text format of visualization is 
text.charAt(0).toUpperCase() + text.substr(1).toLowerCase()

'CPU' changed to 'Cpu'.
I don't think it is necessary to do it.

**Comment by davelandry** [comment]
That is part of `d3plus.string.title`, which is meant to convert a String to titlecase, while respecting both lowercase words like "a" and "of" and also uppercase acronyms like "TV" and "R&D". I did not put in a catch for "CPU", so I will add that in. The new list of uppercase words is as follows:
```js
["CEO", "CFO", "CNC", "COO", "CPU", "HVAC", "R&D", "TV", "UI"]
```

I am also adding in a check for each of those words with an "s" added on the end, so that "CPUs" stays "CPUs". The list of uppercase words can be found [here](https://github.com/alexandersimoes/d3plus/blob/master/src/core/locale/languages/en_US.coffee#L108).

**Comment by davelandry** [comment]
Additionally, you can always override the default text and number formatters: http://d3plus.org/examples/advanced/7760febcda3375b39e1f/

**Comment by zpz1982** [comment]
Thanks. I mean usually user doesn't want his data changed unless he asks. But d3plus changes it by default which really surprises me.
