### ISSUE TITLE
Responsive layout

### ISSUE THREAD

**Issue by bryanph** [alexandersimoes/d3plus#433]
Hey, 

I was looking for a resize feature for dynamic widths and heights depending on the container. I can't seem to find it in the docs. Is this available? If not, I would be willing to make a pull request if you could point out the main pain points in implementing this.

**Comment by curran** [comment]
I'd be curious to hear about the pain points in implementation too. Here's one example that might be relevant here - [bl.ock: Responding to Resize](http://bl.ocks.org/curran/3a68b0c81991e2e94b19)

**Comment by davelandry** [comment]
The concept is fairly simple. Here are the pain points we would need to make sure to address:

**1. detect window resize "stop"**
Triggering the resize event continuously as the page resizes could cause some problems for heavy visualizations and pages with a lot of visualizations. Here's some code I've written in the past to catch for this:
```js
var resize;
function resizeEnd() {
    // resize logic here
}
window.addEventListener("resize", function(){
    clearTimeout(resize);
    resize = setTimeout(resizeEnd, 400);
}
```

**2. account for duplicate event listeners**
I'm not 100% familiar with the current state of cross-browser window event listeners, but in the past I've run into problems where you try to add a listener and it overwrites all other listeners. This may not be an issue now, or we might be able to use D3's classed listeners (`d3.select(window).on("resize.viz1", ...);`). Regardless, we'd need to make sure that multiple visualizations on the same page could all resize independently of eachother.

**3. reset the manually set width and height**
When the window resizes, we'd have to flush out the current container's width and height attributes. D3plus currently sets them [here](https://github.com/alexandersimoes/d3plus/blob/master/src/viz/helpers/container.coffee#L53-L55). As far as I'm aware, the only way to automatically detect the new width and height would be by stripping them from the container itself if the styles are set to "auto".

**4. create a .resize( ) method**
This method should take a boolean, which I would say is true by default, that toggles the resize behavior. Additionally, it should have "timeout" option so that the user can change that `400` ms in the example code above. Methods get created [here](https://github.com/alexandersimoes/d3plus/tree/master/src/viz/methods), and attached [here](https://github.com/alexandersimoes/d3plus/blob/master/src/viz/viz.coffee#L128-L182).

**Comment by MMTLukas** [comment]
+1
