### ISSUE TITLE
detect page touch to remove tooltips

### ISSUE THREAD

**Issue by joaom182** [alexandersimoes/d3plus#434]
On mobile devices, when i touch on Treemap chart for example, tooltip is displayed... but when i touch in another place, the tolltip not disapear.

![image](https://cloud.githubusercontent.com/assets/3612098/13332639/c7f32e4e-dbe1-11e5-87f1-bf4c0025f175.png)

**Comment by davelandry** [comment]
If you touch a different square in the tree map, the tooltip moves to that square, correct?

**Comment by joaom182** [comment]
Yes...

**Comment by davelandry** [comment]
So you are expecting the tooltip to disappear if you click outside of the visualization?

**Comment by joaom182** [comment]
yep

**Comment by Bugget** [comment]
This is a really big issue for us as well.   On Chrome, if a user has a laptop with a touchscreen they have to click on visualizations to see a tool tip instead of hovering.  If they then leave the view without clicking a second time to remove the tooltip the tooltip will stay open.  We have had to add code to remove the tooltip elements added to the page body on navigation to mitigate this.  With new laptops this is become more and more common.

**Comment by davelandry** [comment]
@Bugget the laptop w/ touchscreen issue should have been resolved with version 1.9.0. Can you confirm what version you are currently using?

**Comment by Bugget** [comment]
You are correct Dave, the QA environment is showing d3plus 1.8.0.  I will go get that updated and see what they say about this issue afterwards.  I imagine it will be resolved.  Sorry about that!

**Comment by joaom182** [comment]
On version 1.9.6 is hiding the tooltip, when touch on any spot. Closing this issue.
