### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by pachamaltese** [alexandersimoes/d3plus#501]
Hi

I've been using D3Plus a lot and I have read a lot of things about auto-resize.

I tried to mimic DataViva'a resizing function but it doesn't work with "simple" visualizations. OEC and Data USA have the same resizing method.

I did try a div inside a div, a method called "resize coffee", etc.

I wonder how can activate an auto resize so that when I maximize/minimize the browser the treemaps also resize like the autoresize feature in css (that only works for images)

**Comment by alexandersimoes** [comment]
In the past we've always written our own resize function listening for the window resize event to fire and calculating a new width/height for the viz then.

Looking around the web I was able to find a new SVG element attribute called `preserveAspectRatio` that could allow your viz to be responsive to the page. Of course getting this to work with d3plus would require some hacking...

http://thenewcode.com/744/Making-SVG-Responsive

Let me know if you make any head way on this.

**Comment by pachamaltese** [comment]
thanks a lot !!

I'm gonna try. If I succeed with this resizing, I can release an
implementation of D3Plus in R. Sadly, I'm not a designer and details are
always important.

—————

*Mauricio Vargas Sepúlveda 帕夏*

2016-06-22 1:04 GMT-03:00 Alex Simoes <notifications@github.com>:

**Comment by pachamaltese** [comment]
I did try after some hacks and it very bad compared to Data Viva as I have
to resize, reload and then the figure is resized.

The option "drawing visualization" seems to be the best method but I don't
figure out how to use an argument like .width(100%) in D3Plus





—————

*Mauricio Vargas Sepúlveda 帕夏*

2016-06-22 1:06 GMT-03:00 Mauricio Vargas <mvargassepulveda@gmail.com>:

**Comment by pachamaltese** [comment]
I did try after some hacks and it very bad compared to Data Viva as I have
to resize, reload and then the figure is resized.

The option "drawing visualization" seems to be the best method but I don't
figure out how to use an argument like .width(100%) in D3Plus
![screenshot 2016-06-22 at 12 44 59 am](https://cloud.githubusercontent.com/assets/10091065/16254866/b30012e6-381a-11e6-8b2f-ad71604ccd9c.jpg)

**Comment by davelandry** [comment]
@pachamaltese d3plus should automatically detect the size of the visualization from it's container div, even if it is a percentage.

With [Data USA](www.datausa.io), we add a resize listener to the window, which runs various site resize functions, either instantly or delayed. We delay some functions, like resizing the visualizations, so that we only call the .draw( ) method after the window has stopped being resized. Here is the resize function: https://github.com/DataUSA/datausa-site/blob/master/datausa/html/templates/base.html#L89-L105

And here is where we resize the visualization by setting the container div's dimensions to `"0px"` and both width and height properties of the viz to `false` (in order to let d3plus handle the sizing): https://github.com/DataUSA/datausa-site/blob/master/datausa/assets/js/viz/data/loadBuilds.js#L143-L165

Additionally, v1.9.2 introduced a `.resize(true)` method implemented by @bryanph, which is discussed here: https://github.com/alexandersimoes/d3plus/issues/433

Hope that helps! Really great work on [your R package](https://github.com/pachamaltese/d3plus).

**Comment by pachamaltese** [comment]
Thanks a lot Mr. Landry 

The R package is just the result of my laziness and my constant idea of "spend 48 hours now = automate everything for the next 6 months"

Soon I will add more D3Plus options for the user that wants to write `treemap(data, output) `to obtain his/her treemap on the fly

**Comment by pachamaltese** [comment]
@davelandry Hi!! It won't be bad if you add this option to the new D3plus :)

**Comment by davelandry** [comment]
@pachamaltese what option are you missing in the new d3plus? The `detectResize` method toggles this behavior, and defaults to `true`.

**Comment by pachamaltese** [comment]
Hmm, I cannot get it to work in some specific cases. I must be an specific
idiot or similar.
I'll send reproducible examples!
