### ISSUE TITLE
nested stack plot axis problem with fixed time

### ISSUE THREAD

**Issue by csaladenes** [alexandersimoes/d3plus#541]
When we have a nested stack plot, the axis domain gets multiplied by the number of nested tiers. Eg.: if a unnested data such as .id("a") has its y-axis limits autoset to 0,10, then the nested version .id(["a","b"]) gets limits 0,20, .id(["a","b","c"]) gets limits 0,30, and so on. In V1.7 this was OK, so it is a remnant of the restructuring the Buffer I think...

http://jsbin.com/yeyovumiga/edit?html,output

**Comment by davelandry** [comment]
This problem was introduced with the new behavior of fixing the axes for all-time: https://github.com/alexandersimoes/d3plus/wiki/Visualizations#time

I will be switching the default back to `false` for the next release, but for now you can turn it off manually like this: http://jsbin.com/semacikoto/edit?html,output
