### ISSUE TITLE
nested click events don't work on touch devices

### ISSUE THREAD

**Issue by nalhadad** [alexandersimoes/d3plus#557]
Normally, when clicking on a grouped square, the visusalization will automatically zoom into that group, showing the items within it. on an iPad the click does not have any effect.

**Comment by nalhadad** [comment]
Still waiting for an answer.
thank you

**Comment by mac471** [comment]
I have both an iOS device (iPad) and a Windows 8.1 tablet device for testing.

For a multi-level tree map:
- On the iOS device, when you touch the top level box, it displays the tool tip (which on a mouse/trackpad Macbook Air is displayed any time you hover over the box).  Similar to what @nalhadad posted above, you can't get to the next level of the tree map
- On the Windows tablet, when you touch the top level box, it briefly shows the tool tip and then zooms to the next level in the tree map. But there is no way to just show the tool tip at the top level. If you try to press and hold, IE thinks you are trying to right click and shows you it's menu.

Is there a way for D3plus to know if it is running on a tablet device and if so, could the default behavior be modified so that one "tap" shows the tooltip (that normally shows when the mouse is hovering over a box) and a second "tap" on the text "Click for More Info" on the tool tip then zooms to the next level?

Thanks

**Comment by davelandry** [comment]
This fix will be part of the next release. :beers:
