### ISSUE TITLE
bundling error 

### ISSUE THREAD

**Issue by pachamaltese** [alexandersimoes/d3plus#628]
I cloned the repo and after trying `npm run build` I get this error when I try to build to include the last changes made to `d3plus-plot`

```
[ █▆▅▁ ] bundling build/d3plus.full.js(node:21105) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: 'locale' is not exported by node_modules/d3plus-common/index.js
(node:21105) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

here you can see the changes in `packages.json`: https://github.com/pachamaltese/d3plus/tree/2.0

**Comment by davelandry** [comment]
This error was produced as a result of updating the d3plus-common module, which removed the "locale" export in v0.6.24: https://github.com/d3plus/d3plus-common/releases/tag/v0.6.24

It is fixed by removing the export in the index.js: https://github.com/alexandersimoes/d3plus/commit/e10a1f5d268467be9c3063a3eeddbb5beef2ab9c

As a result of my testing, I have also released a new alpha build with updated dependencies: https://d3plus.org/js/d3plus.v2.0.0-alpha.16.full.min.js
