### ISSUE TITLE
Treemap simple example not work

### ISSUE THREAD

**Issue by poly-sb** [alexandersimoes/d3plus#641]
I've just dowloaded the last version of d3plus and try to run [this](https://d3plus.org/examples/d3plus-hierarchy/selecting-container/) example.

My code cannot be simpler.

```javascript
<div id="viz"></div>
<script src="./js/d3.js"></script>
<script src="./js/d3plus.full.js"></script>
<script>
  var data = [
    {id: "alpha", value: 29},
    {id: "beta",  value: 10}
  ];

  new d3plus.Treemap()
    .data(data)
    .groupBy("id")
    .select("#viz")
    .sum("value")
    .render();
</script>
```
Logs are showing no errors but nothing is showing up on the screen.

I've tested with d3 v.5 v.4 v.3. 

[d3bug.zip](https://github.com/alexandersimoes/d3plus/files/2002255/d3bug.zip)

**Comment by davelandry** [comment]
@poly-sb that example is for the new d3plus 2.0 modules, and you are loading the old 1.0 library. try loading just this 1 file: https://d3plus.org/js/d3plus-hierarchy.v0.6.full.min.js

**Comment by poly-sb** [comment]
Hi @davelandry! By the way, is there a way to change the style and size of the treemap share percentage label?
I saw that the "labelConfig" property allow custom styling of the top label but don't find anything related to the percentage share.

**Comment by davelandry** [comment]
IIRC you can return Arrays from the style methods to correspond with each label. For example:

```js
fontColor: function(d) {
  return ["red", "blue"];
}
```

That should make the text label red, and the share label blue.

**Comment by poly-sb** [comment]
@davelandry Awesome thanks again.

**Comment by talitagoulart** [comment]
Actually this is a bug. The Treemap example works when using [d3plus-hierarchy v0.6](https://d3plus.org/js/d3plus-hierarchy.v0.6.full.min.js) but not when using the [full d3 v2 build](https://d3plus.org/js/d3plus.v2.0.0-alpha.16.full.min.js) or the d3plus v2 installed through npm. Here is a fiddle with the issue: https://jsfiddle.net/wwdkho6x/.

The issue is caused by the way that npm handles the caret in the version. Since the major version is 0, npm treats the minor version as major and doesn't update it.
d3plus package.json defines d3plus-hierarchy version as ["^0.3.12"](https://github.com/alexandersimoes/d3plus/blob/2.0/package.json#L30). When downloading the dependencies, npm only updates the patch version and install the 0.3.14 version, not the 0.6 version.

This behavior is explained in the npm docs: https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004

**Comment by davelandry** [comment]
@talitagoulart ahh yes, the full build hasn't been updated in a while. I just published a new one, can you try it? https://d3plus.org/js/d3plus.v2.0.0-alpha.17.full.js
