### ISSUE TITLE
Treemap - download button - CSS float

### ISSUE THREAD

**Issue by ranucame** [alexandersimoes/d3plus#667]
Hello,
When I set the buttonStyle using CSS "float":"left" the chart is showed over the button. Is there some way to avoid it? 
http://jsfiddle.net/ranucame/tm9xpswe/5/

Thanks

**Comment by davelandry** [comment]
In order to change the alignment of the buttons, you would have to have access to the "text-align" property of the container element, which is currently set manually here: https://github.com/d3plus/d3plus-viz/blob/master/src/_drawControls.js#L108

Made an issue for it here: https://github.com/d3plus/d3plus-viz/issues/99

**Comment by ranucame** [comment]
Thank you!
